### ISSUE TITLE
What needed to prepare if I want to use the custom dataset

### ISSUE THREAD

**Issue by qingfengtommy** [FudanVI/benchmarking-chinese-text-recognition#11]
Thanks for your sharing of the code. I would like to use my own data to train the model.
What should I do? 
My dataset looks like this:

```
Dataset
││
└───TrainDataset
│   │   TrainImg1.jpg
│   │   TrainImg2.jpg
│   │   ......
└───TestDataset
│   │   TestImg1.jpg
│   │   TestImg2.jpg
│   │   ......
└───Label.json ( includes the bbox and the character labels for train and test dataset)
```

**Comment by JingyeChen** [comment]
Thanks for your attention for this work! Currently the code mainly support the lmdb files. You could refer to https://github.com/FudanVI/benchmarking-chinese-text-recognition/blob/main/data/lmdbMaker.py to construct your lmdb datasets.
