### ISSUE TITLE
Please upload the supported files.

### ISSUE THREAD

**Issue by qingfengtommy** [FudanVI/benchmarking-chinese-text-recognition#12]
There are some supported file doesn't upload in this repo.:
```
parser.add_argument('--alpha_path', type=str, default='./data/benchmark.txt', help='')
parser.add_argument('--alpha_path_radical', type=str, default='./data/radicals.txt', help='')
parser.add_argument('--decompose_path', type=str, default='./data/decompose.txt', help='')
```

Thanks!

**Comment by hyangyu** [comment]
> There are some supported file doesn't upload in this repo.:
> 
> ```
> parser.add_argument('--alpha_path', type=str, default='./data/benchmark.txt', help='')
> parser.add_argument('--alpha_path_radical', type=str, default='./data/radicals.txt', help='')
> parser.add_argument('--decompose_path', type=str, default='./data/decompose.txt', help='')
> ```
> 
> Thanks!

Please refer to https://github.com/FudanVI/benchmarking-chinese-text-recognition/tree/main/model/TransOCR/data. Please check the files of each baseline model.

**Comment by qingfengtommy** [comment]
> > There are some supported file doesn't upload in this repo.:
> > ```
> > parser.add_argument('--alpha_path', type=str, default='./data/benchmark.txt', help='')
> > parser.add_argument('--alpha_path_radical', type=str, default='./data/radicals.txt', help='')
> > parser.add_argument('--decompose_path', type=str, default='./data/decompose.txt', help='')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks!
> 
> Please refer to https://github.com/FudanVI/benchmarking-chinese-text-recognition/tree/main/model/TransOCR/data. Please check the files of each baseline model.

Thanks!
