### ISSUE TITLE
SCUT-HCCDoc

### ISSUE THREAD

**Issue by lyc728** [FudanVI/benchmarking-chinese-text-recognition#3]
你好，请问有关这个手写体数据集的解压密码吗？对于手写体数据，SCUT-EPT也是手写体，请问为什么没有加入训练呢？

**Comment by JingyeChen** [comment]
非常感谢您的关注！解压密码详见https://github.com/HCIILAB/SCUT-HCCDoc_Dataset_Release，我们在选择handwriting dataset的时候考虑到很多数据集，但是由于不同数据集存在明显的domain gap问题最终只选择了SCUT-HCCDoc

**Comment by lyc728** [comment]
感谢你的回复，我很早按照格式进行发送邮件，但是没有得到解压密码，烦请你提供一下，十分感激，2529706061@qq.com

**Comment by JingyeChen** [comment]
密码我这边没有办法提供，不好意思
